apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{template "annotator.name" .}}-env"
  labels:
    app: annotator
data:
  MONGODB_HOST: "{{template "mongodb.url" .}}"
  CELERY_BROKER_URL: "{{template "broker.url" .}}"
  CELERY_RESULT_BACKEND: "{{template "mongodb.url" .}}"
