apiVersion: v1
kind: Service
metadata:
  name: webserver
  labels:
    app: {{ template "annotator.name" . }}
    component: webserver
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "annotator.name" . }}
    component: webserver
    release: {{ .Release.Name }}
  ports:
  - name: webserver
    protocol: TCP
    port: 5000
    targetPort: 5000
status:
  loadBalancer: {}
